[package]
name = "marketplace-builder-core"
version = "0.0.1"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-broadcast = "0.7"
async-compatibility-layer = { version = "1.2.1", default-features = false, features = [
    "logging-utils",
] }
async-lock = "2.8"
async-std = { version = "1.9.0", features = ["unstable", "attributes"] }
async-trait = "0.1"
clap = { version = "4.4", features = ["derive", "env"] }
committable = "0.2"
derivative = "2.2"
espresso-types = { git = "https://github.com/EspressoSystems/espresso-sequencer.git",  features = [
    "testing",
], rev ="a31c0bca53e2b46e47f913085e0cf3efe56bdcc6" }
ethers = { version = "2.0.4" }
futures = "0.3"
hotshot = { git = "https://github.com/EspressoSystems/HotShot.git", branch = "ag/bundle" }
hotshot-builder-api = { git = "https://github.com/EspressoSystems/HotShot.git", branch = "ag/bundle" }
hotshot-events-service = { git = "https://github.com/EspressoSystems/hotshot-events-service.git", branch = "ag/bundle" }
hotshot-task-impls = { git = "https://github.com/EspressoSystems/HotShot.git", branch = "ag/bundle" }
hotshot-types = { git = "https://github.com/EspressoSystems/HotShot.git", branch = "ag/bundle" }
# TODO: remove once sequencer is up-to-date
hotshot-types-old = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "rc-0.5.64", package = "hotshot-types" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
snafu = "0.8"
surf-disco = "0.9"
tagged-base64 = "0.4"
tide-disco = "0.9"
tokio = "1"
toml = "0.8"
tracing = "0.1"
url = "2.3"
vbs = "0.1"
multimap = "0.10.0"

[dev-dependencies]
hotshot-example-types = { git = "https://github.com/EspressoSystems/HotShot.git", branch = "ag/bundle" }
