[workspace]
resolver = "2"
members = [
  "crates/*"
]

[workspace.dependencies]
hotshot = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.72" }
hotshot-builder-api = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.72" }
hotshot-events-service = { git = "https://github.com/EspressoSystems/hotshot-events-service.git", tag = "0.1.44" }
hotshot-task-impls = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.72" }
hotshot-types = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.72" }

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(async_executor_impl, values("async-std", "tokio"))',
] }
