[workspace]
resolver = "2"
members = [
  "crates/*"
]

[workspace.dependencies]
hotshot = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.74", features = ["dependency-tasks"] }
hotshot-builder-api = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.74" }
hotshot-events-service = { git = "https://github.com/EspressoSystems/hotshot-events-service.git", tag = "0.1.46" }
hotshot-task-impls = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.74", features = ["dependency-tasks"] }
hotshot-types = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.74" }
hotshot-example-types = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "0.5.74" }

anyhow = "1"
async-broadcast = "0.7"
async-compatibility-layer = { version = "1.2.1", default-features = false }
async-lock = "2.2"
async-std = "1.9.0"
async-trait = "0.1"
bincode = "1.3"
clap = "4.5"
committable = "0.2"
derivative = "2.2"
either = "1.13"
futures = "0.3"
hex = "0.4.3"
lru = "0.12.3"
multimap = "0.10.0"
serde = "1.0"
serde_json = "1.0"
sha2 = "0.10"
snafu = "0.8"
surf-disco = "0.9"
tagged-base64 = "0.4"
tide-disco = "0.9"
tokio = "1"
toml = "0.8"
tracing = "0.1"
url = "2.3"
vbs = "0.1"
rkyv = "0.7"

[workspace.package]
version = "0.1.47"
edition = "2021"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(async_executor_impl, values("async-std", "tokio"))',
] }
