[meta]
NAME = "marketplace-builder"
DESCRIPTION = "Espresso Marketplace Builder"

[route.submit_bid]
PATH = ["bundle/:view_number"]
":view_number" = "Integer"
METHOD = "POST"
DOC = """
Fetch the bundle from the builder for the specified view.
"""