name: Nix

on:
  push:
    branches:
      - main
      - release-*
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  nix:
    strategy:
      matrix:
        flags: ["--cfg legacy_builder_refactored", ""]
    env:
      RUSTFLAGS: "${{ matrix.flags }}"
      RUSTDOCFLAGS: "${{ matrix.flags }}"
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Nix environment loads
        run: nix develop -c echo Success

      - name: Nix environment builds all targets
        run: nix develop -c cargo build --all-targets --all-features --release --workspace

      - name: Precommit hooks work
        run: nix develop -c pre-commit run --all-files
