name: Build

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: '--cfg async_executor_impl="async-std" --cfg async_channel_impl="async-std"'
      RUST_LOG: info
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@nextest

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build
        run: cargo build --workspace --release

      - name: Run doctests
        run: cargo test --workspace --release --doc

      - name: Run tests
        run: |
          cargo nextest run --workspace --release  -j 2 \
            --lib --bins --tests --benches --all-features \
            --verbose --no-fail-fast
        timeout-minutes: 60
