name: Combine PRs

on:
  schedule:
    - cron: "0 1 * * MON"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - id: combine-prs
        uses: github/combine-prs@v5.0.0
        with:
          labels: "dependabot,combined-pr"
