name: Coverage

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - uses: cachix/cachix-action@v15
        # If PR is from a non-collaborator (e.g. dependabot) the secrets are missing and the login to cachix fails.
        continue-on-error: true
        with:
          name: espresso-systems-private
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community
          skipPush: ${{ github.actor == 'dependabot[bot]' }}

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Generate coverage reports
        run: |
          git config --global --add safe.directory "$PWD"
          nix develop .#perfShell -c \
            cargo llvm-cov nextest -j 2 --release --all-features --all-targets \
                           --branch --lcov --output-path lcov.info \

      - uses: coverallsapp/github-action@master
        with:
          path-to-lcov: lcov.info
