name: Coverage

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Enable Cachix
        uses: cachix/cachix-action@v15
        # If PR is from a non-collaborator (e.g. dependabot) the secrets are missing and the login to cachix fails.
        continue-on-error: true
        with:
          name: espresso-systems-private
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community
          skipPush: ${{ github.actor == 'dependabot[bot]' }}

      - name: Cache cargo
        uses: actions/cache@v4.1.1
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
            target
          key: hs-builder-core-codecov-v1-${{ hashFiles('Cargo.lock') }}

      - name: Generate coverage reports
        run: |
          git config --global --add safe.directory "$PWD"
          nix develop .#perfShell -c cargo llvm-cov --profile=release --all-features --all-targets --lcov --output-path lcov.info -- --test-threads 1

      - name: Coveralls upload
        uses: coverallsapp/github-action@master
