name: Lint

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: '--cfg async_executor_impl="async-std" --cfg async_channel_impl="async-std"'
      RUSTDOCFLAGS: '--cfg async_executor_impl="async-std" --cfg async_channel_impl="async-std"'
      RUST_LOG: info
    steps:
      - uses: styfle/cancel-workflow-action@0.12.0
        name: Cancel Outdated Builds
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4
        name: Checkout Repository

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching

      - name: Format check
        run: cargo fmt -- --check

      - uses: actions-rs/clippy-check@v1
        name: Clippy
        with:
          token: ${{ github.token }}
          args: --workspace --no-default-features --all-features --all-targets -- -D warnings

      - name: Check docs
        run: |
          cargo doc --no-deps --workspace --document-private-items --all-features
