name: Lint

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      RUST_LOG: info
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Format check
        run: cargo fmt -- --check

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ github.token }}
          args: --workspace --no-default-features --all-features --all-targets -- -D warnings

      - name: Check docs
        run: |
          cargo doc --no-deps --workspace --document-private-items --all-features
