name: Test

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    env:
      RUST_LOG: info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@nextest

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build
        run: cargo build --workspace --release

      - name: Run doctests
        run: cargo test --workspace --release --doc

      - name: Run tests
        run: |
          cargo nextest run --workspace --release  -j 2 \
            --lib --bins --tests --benches --all-features \
            --verbose --no-fail-fast
        timeout-minutes: 60

  test-ignored:
    runs-on: ubuntu-latest
    env:
      RUST_MIN_STACK: 64000000
      RUST_LOG: info
    steps:
      - uses: styfle/cancel-workflow-action@0.12.0
        name: Cancel Outdated Builds
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4
        name: Checkout Repository

      - uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@nextest

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching

      - name: Run slow tests
        run: |
          cargo nextest run --workspace --release  -j 1 \
            --lib --bins --tests --benches --all-features \
            --verbose --no-fail-fast --run-ignored only
        timeout-minutes: 60
